import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getPost, getRelatedPosts } from '../posts';
import { BlogPostContent } from './BlogPostContent';

// Base URL for social cards
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'https://lockin.bot';

interface PageProps {
  params: Promise<{ slug: string }>;
}

/**
 * Generate metadata for social cards (Open Graph, Twitter)
 */
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const post = getPost(slug);

  if (!post) {
    return {
      title: 'Post Not Found | LockIn Blog',
    };
  }

  const { metadata } = post;

  // Use custom social fields if provided, otherwise fall back to defaults
  const socialTitle = metadata.socialTitle || metadata.title;
  const socialDescription = metadata.socialDescription || metadata.excerpt;

  // Note: OG and Twitter images are automatically generated by opengraph-image.tsx and twitter-image.tsx
  return {
    title: `${metadata.title} | LockIn Blog`,
    description: metadata.excerpt,
    authors: [{ name: metadata.author.name }],
    openGraph: {
      title: socialTitle,
      description: socialDescription,
      type: 'article',
      publishedTime: metadata.date,
      authors: [metadata.author.name],
      url: `${BASE_URL}/blog/${metadata.slug}`,
      siteName: 'LockIn',
      // Images are auto-generated from opengraph-image.tsx
    },
    twitter: {
      card: 'summary_large_image',
      title: socialTitle,
      description: socialDescription,
      creator: '@thelockinbot',
      // Images are auto-generated from twitter-image.tsx
    },
  };
}

/**
 * Generate static params for all blog posts
 * Note: We hardcode slugs here to avoid importing client components during build
 */
export function generateStaticParams() {
  // List all post slugs - add new slugs here when adding posts
  const slugs = [
    'introducing-lockin',
    'how-to-build-ai-without-giving-up-privacy',
  ];

  return slugs.map((slug) => ({ slug }));
}

export default async function BlogPostPage({ params }: PageProps) {
  const { slug } = await params;
  const post = getPost(slug);

  if (!post) {
    notFound();
  }

  const relatedPosts = getRelatedPosts(slug, 2);
  const { Content } = post;

  return (
    <BlogPostContent
      metadata={post.metadata}
      relatedPosts={relatedPosts.map(p => p.metadata)}
    >
      <Content />
    </BlogPostContent>
  );
}
